<%@ Page Title="Registrazione dati" Language="C#" MasterPageFile="~/MasterPage.Master" AutoEventWireup="true" CodeBehind="Registrazione.aspx.cs" Inherits="WebFormDB.Registrazione" %>

<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">

</asp:Content>


<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">


    <div class="container">

        <h1>Ultimo Ordine</h1>
        <%--OnItemInserting="DetailsView1_ItemInserting"--%>
    <asp:DetailsView ID="DetailsView1" CssClass="footable" runat="server" DataKeyNames="Id,Descrizione,Id_Cliente" DataSourceID="SqlDataSource1" AutoGenerateRows="false" AllowPaging="true" AutoGenerateInsertButton="true" Height="50px" Width="125px"
        >
        <Fields>
            <asp:BoundField DataField="Id" HeaderText="Id" />
            <asp:BoundField DataField="Descrizione" HeaderText="Descrizione" />
            <asp:TemplateField HeaderText="Nome Cliente" SortExpression="Id_Cliente">
                <ItemTemplate>
                    <%#Eval("Id_Cliente")%>
                </ItemTemplate>
                <InsertItemTemplate>
                    <asp:DropDownList ID="LocationDropDown" runat="server" DataValueField="Id" DataSourceID="SqlDataSource2" ClientIDMode="Static" DataTextField="Nome" />
                </InsertItemTemplate>
            </asp:TemplateField>
        </Fields>
        <PagerSettings PageButtonCount="4" Position="Top" />
    </asp:DetailsView>

    </div>


    <div class="container">

        <h1>Nuovo ordine</h1>

        
        <asp:GridView ID="GridView2" CssClass="footable" runat="server"  DataSourceID="SqlDataSource1" AutoGenerateColumns="false" AutoGenerateEditButton="true" Style="max-width: 500px">
    
    <Columns>
        <asp:BoundField DataField="Id" HeaderText="Id" />
        <asp:BoundField DataField="Descrizione" HeaderText="Descrizione" />
        <asp:BoundField DataField="Id_Cliente" HeaderText="Cliente ID" />
    </Columns>

    </asp:GridView>

       

        
    </div>

    <hr />

    <!-- Collegamento al DB MySQL tramite ID-->

    <asp:SqlDataSource ID="DsCliente" runat="server" ConnectionString="<%$ ConnectionStrings:MyConnectionString %>"
                                ProviderName="<%$ ConnectionStrings:MyConnectionString.ProviderName %>"
                                SelectCommand="SELECT * FROM Ordini"
                                UpdateCommand="UPDATE Ordini SET descrizione=@descrizione, Id_Cliente=@Id_Cliente where Id=@Id" 
                                DeleteCommand="DELETE FROM Ordini WHERE Id = @Id"
                                >
                                
                            </asp:SqlDataSource>


                                         <!-- se cambi DB togli [] da insert -->
    <asp:SqlDataSource ID="SqlDataSource1" runat="server" ConnectionString="<%$ ConnectionStrings:MyConnectionString %>"
                                ProviderName="<%$ ConnectionStrings:MyConnectionString.ProviderName %>"
                                SelectCommand="SELECT * FROM Ordini ORDER BY Id DESC"
                                InsertCommand="INSERT INTO Ordini (Descrizione, Id_Cliente)
                                                VALUES (@Descrizione, @Id_Cliente)"
                                >
                                    <InsertParameters>
                                        <asp:ControlParameter ControlID="DetailsView1$LocationDropDown" Name="Id_Cliente" />
                                    </InsertParameters>
                                
                            </asp:SqlDataSource>

    <asp:SqlDataSource ID="SqlDataSource2" runat="server" ConnectionString="<%$ ConnectionStrings:MyConnectionString %>"
                                ProviderName="<%$ ConnectionStrings:MyConnectionString.ProviderName %>"
                                SelectCommand="SELECT Id, Nome FROM Clienti ORDER BY Id DESC"
                                
                                >
                                
                            </asp:SqlDataSource>

    

    <br />

    <div class="container">

        <h1>Tabella Ordini</h1>
    
    <asp:GridView ID="GridView1" CssClass="footable" runat="server" DataKeyNames="Id" DataSourceID="DsCliente" AutoGenerateColumns="false" AutoGenerateDeleteButton="true" AutoGenerateEditButton="true" Style="max-width: 500px">
    
    <Columns>
        <asp:BoundField DataField="Id" HeaderText="Id" />
        <asp:BoundField DataField="Descrizione" HeaderText="Descrizione" />
        <asp:BoundField DataField="Id_Cliente" HeaderText="Cliente ID" />
    </Columns>

    </asp:GridView>
 
    </div>

    <!-- script per tabella-->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/jquery-footable/0.1.0/css/footable.min.css"
    rel="stylesheet" type="text/css" />
    <script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery-footable/0.1.0/js/footable.min.js"></script>
    <script type="text/javascript">
    $(function () {
        $('[id*=GridView1]').footable();
        $('[id*=DetailsView]').footable();
    });
    </script>
    
</asp:Content>
